### ISSUE TITLE
transfer to ropensci

### ISSUE THREAD

**Issue by maelle** [ropensci/dbhydroR#14]
:wave: @jsta we no longer transfer onboarded packages to ropenscilabs but instead directly to ropensci so we should move this repo. Are you ok with my doing it? If so when would you have the time to update all links? I wouldn't transfer before you have time to do that, and it's not urgent to transfer anyway.

If possible could you please add this badge to the README of rnaturalearth when updating CI links?
`[![Project Status: Active – The project has reached a stable, usable state and is being actively developed.](http://www.repostatus.org/badges/latest/active.svg)](http://www.repostatus.org/#active)`

Thanks for your patience! 🙏

**Comment by jsta** [comment]
Sounds good @maelle. I am about to change the links to `ropensci`. This repo already has a repostatus badge, was your note a copy-paste mistake.?

**Comment by maelle** [comment]
Thanks a lot, transferred! :rocket: And yes sorry I hadn't seen the badge 🙈
