### ISSUE TITLE
function get_hydro() broken

### ISSUE THREAD

**Issue by fantanaman** [ropensci/dbhydroR#15]
Returns error apparently for any and all dbkey and date range inputs. In the example below, data for the given dbkey can be successfully retrieved from DBHydro through the web interface. 

> get_hydro(dbkey = "HC940", date_min = "2018-05-01", date_max = "2018-05-02")
Error in get_hydro(dbkey = "HC940", date_min = "2018-05-01", date_max = "2018-05-02") : 
  No data found

**Comment by jsta** [comment]
I can confirm this, thanks for the report. Pushing a fix shortly.

**Comment by fantanaman** [comment]
`get_hyrdo`  worked immediately after updating to v0.2-6 on 2018-07-19. As of 2018-07-20, getting the same error as reported above.

**Comment by jsta** [comment]
It works for me. 

```
get_hydro(dbkey = "HC940", date_min = "2018-05-01", date_max = "2018-05-02")

> 1 2018-05-01                 9.13
> 2 2018-05-02                 9.08
```

Can you confirm that you have 0.2-6 loaded? 
```
packageVersion("dbhydroR")

> [1] ‘0.2.6’
```

**Comment by fantanaman** [comment]
You are quite right, it is working. I was testing on behalf of colleague who reported it not working. I since discovered typo in my dbkey value, that was causing my error. He since solved his issue by uninstalling/reinstalling package. Apologies for bumping this thread unnecessarily. 

Thank you for the great tool.
