### ISSUE TITLE
function get_hydro() broken (again)

### ISSUE THREAD

**Issue by fantanaman** [ropensci/dbhydroR#16]
`get_hydro` returns error for any and all dbkey and date range inputs. An example taken from the documentation (but updated to an active dbkey value):
```r
> get_hydro(dbkey = "HC940",
           date_min = "2013-01-01", date_max = "2013-02-02")
```
> Error in get_hydro(dbkey = "HC940", date_min = "2013-01-01", date_max = "2013-02-02") : 
  No data found
In addition: Warning message:
In min(which(apply(raw[, 10:16], 1, function(x) all(is.na(x))))) :
  no non-missing arguments to min; returning Inf

Data, including from this example, are accessible from the DBHydro web interface. 

`get_dbkey()` and `get_wq()` appear to be functioning correctly.

**Comment by jsta** [comment]
Thanks for the bug report! Should be fixed now if you update to the development version `devtools::install_github("ropensci/dbhydroR")`. Pushing new version to CRAN soon.
